### ISSUE TITLE
Add "scale" functionality to isosurfaces

### ISSUE THREAD

**Issue by siegfriedkaidisch** [brands-d/blentom#2]
When reading a cube file produced by Fiesta, the plotted isosurface is too large. This is due to the units used by Fiesta. At the moment, I scale the isosurface (in this case a wavefuction), like this:

```python
wf = Wavefunction.read(dir_ / filename,level=0.01)
scale_factor = 0.529177249 #Bohr->Angstroem
scale_factors = [scale_factor for i in range(3)]
for wfpart in wf.wavefunction_parts:
    wfpart.blender_object.scale = scale_factors
```

A "scale" method for the isosurface class, that takes only one argument (or maybe three?), could be useful.

**Comment by brands-d** [comment]
Done
